name: Java/Gradle CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@859c33240bd026ce8d5f711f5adcc65c2f8eafc1
      - name: Build with Gradle
        run: ./gradlew build
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: .build/publish.sh
        env:
          GPG_SECRET: ${{ secrets.GPG_SECRET }}